### ISSUE TITLE
Cutover plan for mozqa.com

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/scl3-migration-project#10]
We see a haul deployment of this.

- https://docs.google.com/document/d/15p-rACr2w3DkGoJEdJsX6o7_sCCpHwDvMD9AK0ypZmA/edit?usp=sharing

- Find out if they still need the "bad certs" (host names were crossed out in the doc)
- Can this be hosted on Haul?

Meet with the service owner and figure out what the project is at this point.

**Comment by danielhartnell** [comment]
Sent an email to the owner. Currently waiting for a response.

**Comment by danielhartnell** [comment]
I would not recommend Haul for this specific site if we need to continue to serve self-signed SSL certificates and HTTP-only responses.

**Comment by mgreensmith** [comment]
Shyam mentioned in the SCL3 meeting today that the TLS cert/bad domain stuff is migrating to other services, and doesn't need to be part of this work. Those subdomains can stay at SCL3 for now. The only thing we need to move is the static site content at the root/www domain.

**Comment by danielhartnell** [comment]
Perfect. Thank you.

**Comment by danielhartnell** [comment]
Status report conclusion:

- Update Haul so it no longer points at gozer's fork: https://github.com/mozilla-it/haul/blob/master/sites/mozqa.groovy#L7-L10
- I took a quick look at the prod site access logs, grabbed the paths requested and validated that we go the same responses from gozer's site in Haul. Looks good to me
- Sounds like we only need www.mozqa.com and mozqa.com certs so we're good to go in the Traefik config

I think we're ready to continue with the migration as we communicate the change to the appropriate people.

**Comment by mgreensmith** [comment]
- [ ] Site content in AWS is identical to content served from the datacenter Use a tool like https://github.com/evolvingweb/sitediff or do it manually.
- [ ] All required HTTP headers are present (as compared to the datacenter site)
- [ ] The site has been audited through Observatory an has an acceptable score.
- [ ] Site content is sourced from the canonical github repo, not a personal fork.
- [ ] MOC has a basic monitor for the site and a runbook for incident management.
- [ ] DNS has been audited and we know all of the domains that point to the app, TTLs are set low
- [ ] We are serving correct TLS certificates for production domains.
- [ ] Some capacity planning based on current production traffic. Review Zeus logs, New Relic, Apache logs

**Comment by danielhartnell** [comment]
Notes on my progess:

- The site content is not identical. I discovered that the production site has not been pulling in updates from GitHub. We'll pull in some changes since 2013 with this migration and that's certainly not a bad thing. Other than that, I think I'm comfortable saying that the content matches as well as it can.

- I removed response headers which will drop our Observatory score from a B to an F to match the production site today. We'll keep parity with the current prod site and we can work with the site owner to improve the Observatory score afterward. I want to make sure we don't break any existing functionality by adding headers without effectively testing.

https://github.com/mozilla-it/haul/pull/137

- It turns out there was no mozqa.com GitHub repository to fork. This was created by gozer and I asked him to move it to the the mozilla-itcloud organization.

- The Apache config loads an htaccess file in one subdirectory and this is returning internal server errors because of an issue parsing that config file. A PR for a fix is here: https://github.com/jds2501/webapi-permissions-tests/pull/2

- Asking the MOC to monitor the site: https://bugzilla.mozilla.org/show_bug.cgi?id=1476122

- Based on the traffic estimates pulled from Zeus, we might see approximately 1,000 requests per day which is pretty low and we should have no issues handling within Haul.

**Comment by danielhartnell** [comment]
Updates:

I'm not planning on bringing this to CAB tomorrow so the migration will need to wait about a week. Once I get approval from the website owner, I will file a change for CAB. I also need to get this PR merged to fix an Apache internal server error when it tries to read the `.htaccess` file.

https://github.com/jds2501/webapi-permissions-tests/pull/2

Also waiting for monitoring to be setup in https://bugzilla.mozilla.org/show_bug.cgi?id=1476122.

**Comment by danielhartnell** [comment]
Following the email thread, I think it is safe to close this. I can re-open it if needed. Status: not migrating the site.
